<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="footer-col">
        <h4>Project</h4>
        <ul>
          <li><a href="#">This is a Website about the programming language 'Ruby on Rails' created for the COS10026 class group assesment</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Participants</h4>
        <ul>
          <li><a href="mailto:103990434@student.swin.edu.au">Manwel QARYAQOS</a></li>
          <li><a href="mailto:103796085@student.swin.edu.au">Md Fazlay Rabbi</a></li>
          <li><a href="mailto:103832125@student.swin.edu.au">Elisha Vihanga Wijesingha</a></li>
          <li><a href="mailto:103820052@student.swin.edu.au">Sariya Akhter Lura</a></li>
          <li><a href="mailto:103843978@student.swin.edu.au">Minh Duy Vu</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Menu</h4>
        <ul>
          <li><a href= "index.php">Home</a></li>
          <li><a href= "topic.php">Topic</a></li>
          <li><a href="quiz.php">Quiz</a></li>
          <li><a href="enhancements.php">Enhancements</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Source</h4>
        <ul>
          <li><a href="https://www.codecademy.com/" target="_blank">Code Academy</a></li>
          <li><a href="https://www.devcamp.com/" target="_blank">Devcamp</a></li>
          <li><a href="https://www.wikipedia.org/" target="_blank">Wikipedia</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<!-- footer ends here -->
</body>
</html>