<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="description" content="Creating Web Applications"/>
  <meta name="keywords" content="HTML, CSS"/>
  <meta name="author" content="Group 3"/>
  <link rel="stylesheet" type="text/css" href="styles/style.css">
  <title>Ruby on Rails</title>
</head>
<body class="Site">
  <!-- header starts here -->
  <header>
    <div class="wrapper">
      <div class="logo">
        <img src= "images/logo.png" alt="logo"> 
      </div>
      <nav>
        <ul class="nav-area">
          <li><a href= "index.php">Home</a></li>
          <li><a href= "topic.php">Topic</a></li>
          <li><a href="quiz.php">Quiz</a></li>
          <li><a href="enhancements.php">Enhancements</a></li>
          <li><a href="https://www.youtube.com/watch?v=w58nbA9NSTQ">YouTube Video</a></li>
        </ul>
      </nav>
    </div>
  </header>